spring:
  datasource:
    url: jdbc:h2:~/data/buybook
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: jdbc:${DATABASE_URL}
